version: 0.{build}
image: Visual Studio 2017
configuration: Release

install:
  - cmd: nuget restore -verbosity quiet
  - ps: gitversion /l console /output buildserver

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  version: '{version}'
  assembly_version: '{version}'
  informational_version: '{version}'

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal

test:
  assemblies:
    only:
    - '**\*.Test.dll'

deploy: off
