version: 4.0.{build}
image: Visual Studio 2015
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore -verbosity quiet

build:
  parallel: true
  verbosity: minimal

test:
  assemblies: '**\*.Test.dll'